# ~/.config/yazi/yazi.toml

[mgr]
ratio = [2,4,4]

show_hidden = true
show_symlink = true

sort_by = "extension"
sort_sensitive = false
sort_dir_first = true

linemod = "size"

mouse_events = ["click", "scroll"]

[input]
cursor_blink = true
